# Use postgres/example user/password credentials
version: '3.1'

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./static/:/code/static/ 
      - ./media/:/code/media/


  web:
    build: .
    ports:
      - 8001:8000
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - "db"
    env_file:
      - .env



  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env




  redisdb:
    image: redis
    ports:
      - 6379:6379

  celery:
    build: . 
      # context: .
      # dockerfile: celery.dockerfile
    volumes:
      - ./media:/code/media
    command: celery -A e_commerce worker -l info -P gevent
    depends_on:
      - "db"
      - "redisdb"
    env_file:
      - .env

  celery-beat:
    build: . 
      # context: .
      # dockerfile: celery.dockerfile
    volumes:
      - ./media:/code/media
    command: celery -A e_commerce  beat -l info -S django
    depends_on:
      - "db"
      - "redisdb"
    env_file:
      - .env