# Use postgres/example user/password credentials
version: '3.1'

services:




  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: Fariz
      POSTGRES_DB: E_commerce


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  redisdb:
    image: redis
    ports:
      - 6379:6379



  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./static/:/code/static/ 
  #     - ./media/:/code/media/




  # web:
  #   build: . 
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./media:/code/media
  #   depends_on:
  #     - "db"
  #   env_file:
  #     - .env

  # celery:
  #   build: . 
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./media:/code/media
  #   depends_on:
  #     - "db"
  #   env_file:
  #     - .env


