# Generated by Django 4.1.3 on 2022-11-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug'),
        ('product', '0002_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='property', to='product.category'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.abstractmodel')),
                ('path', models.ImageField(upload_to='product_image')),
                ('is_main', models.BooleanField(default=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            bases=('blog.abstractmodel',),
        ),
    ]
