# Generated by Django 4.1.3 on 2022-11-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productpropertyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertyvalue',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
