# Generated by Django 4.1.3 on 2022-11-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug'),
        ('product', '0006_product_propert_value_alter_productimages_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='propert_value',
        ),
        migrations.CreateModel(
            name='ProductPropertyValue',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.abstractmodel')),
                ('count', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('property_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.propertyvalue')),
            ],
            bases=('blog.abstractmodel',),
        ),
    ]
