# Generated by Django 4.1.3 on 2022-11-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_propert_value_productpropertyvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_property', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='property_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_property', to='product.propertyvalue'),
        ),
    ]
