# Generated by Django 4.1.3 on 2022-11-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='review',
            field=models.CharField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], max_length=1),
        ),
    ]
