# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ../pgdb:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - ../.env
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # redisdb:
  #   image: redis
  #   ports:
  #     - 6380:6379