# Generated by Django 4.1.3 on 2022-11-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='cities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shipping_City', to='order.city'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='countries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shipping_Country', to='order.country'),
        ),
    ]
