# Generated by Django 4.1.3 on 2022-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_basket_order_customer_basketi̇tem'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='tot_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basketi̇tem',
            name='tot_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
