# Generated by Django 4.1.3 on 2022-11-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_basket_tot_price_alter_basket_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='tot_price',
            new_name='total_price',
        ),
    ]
