# Generated by Django 4.1.3 on 2022-11-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
    ]
