# Generated by Django 4.1.3 on 2022-11-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_user_basket_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketi̇tem',
            name='tot_price',
        ),
    ]
